version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    image: celery-tasks
    build:
      context: .
      dockerfile: ./Dockerfile.celery
    depends_on:
      - redis
  app:
    image: flask-api
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "5000:5000"
    depends_on:
      - celery
